//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dfe.Edubase2.SoapApi.Client.EdubaseService {
    using System.Runtime.Serialization;
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EdubaseFileManagerChannel : Dfe.Edubase2.SoapApi.Client.EdubaseService.EdubaseFileManager, System.ServiceModel.IClientChannel {
    }
}
